# ==================== ???????? ????????? ?????????? ====================
spring.application.name=zoo-bot

# ==================== Telegram Bot ====================
telegram.bot.token=8542773459:AAGL1CACFXkkHEYqdDDZPeduSQfGCCG_aVI
telegram.bot.username=@yfayrzoo_bot

# ==================== ???? ?????? (H2 ??? ??????????) ====================
spring.datasource.url=jdbc:h2:mem:zoo_bot;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (??? ???????? ??????? ? ????? ??????? ? ???????? http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# ==================== ??????????? ====================
logging.level.root=INFO
logging.level.com.example.zoo_bot=DEBUG
logging.level.org.telegram=INFO

# ?????????
server.servlet.encoding.charset=UTF-8

# ID ???? ?????????? (????? ??????? ?????? ??? ?????? ??? ?????????)
telegram.volunteer.chat-id=
